# model settings
model:
  name: seal_removal_denoiser
  version: '1'

# server settings
server:
  url: 192.168.0.104:8001
  verbose: 
  ssl:
  root_certificates:
  private_key:
  certificate_chain:
  client_timeout:
  grpc_compression_algorithm:

